import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.getByText('Individual').click();
  await page.locator('#disclaimer').check();
  await page.getByRole('textbox', { name: '-....-....' }).click();
  await page.getByRole('textbox', { name: '-....-....' }).fill('968980563151');
  await page.locator('#panNo').click();
  await page.locator('#panNo').fill('DRFGY4576h');
  await page.locator('#voterId').click();
  await page.getByRole('button', { name: 'Check if existing customer' }).click();
  await page.getByRole('button', { name: 'New' }).click();
  await page.locator('#appName').nth(1).click();
  await page.locator('#appName').nth(1).fill('Regression Testing');
  await page.getByRole('textbox', { name: 'dd/mm/yyyy' }).click();
  await page.getByRole('button', { name: '2026' }).click();
  await page.getByRole('button', { name: '‹' }).click();
  await page.getByRole('button', { name: '‹' }).click();
  await page.getByText('1993').click();
  await page.getByText('August').click();
  await page.getByText('18', { exact: true }).click();
  await page.getByText('Male', { exact: true }).click();
  await page.locator('sai-input').filter({ hasText: 'Father / Husband name *' }).locator('#fatherHusbName').click();
  await page.locator('sai-input').filter({ hasText: 'Father / Husband name *' }).locator('#fatherHusbName').fill('Ramkumar');
  await page.locator('input[name="altMobnumber"]').click();
  await page.locator('input[name="altMobnumber"]').fill('895-435-47868');
  await page.getByRole('textbox', { name: 'Enter Email ID' }).click();
  await page.getByRole('textbox', { name: 'Enter Email ID' }).fill('shanmugaraj.maniyarasan@sysarcinfomatix.com');
  await page.getByText('Agri').click();
  await page.getByText('Govt').click();
  await page.locator('input[name="tenure"]').click();
  await page.locator('input[name="tenure"]').fill('12');
  await page.getByText('Owned').click();
  await page.locator('input[name="resYears"]').click();
  await page.locator('input[name="resYears"]').fill('4');
  await page.getByText('Married', { exact: true }).click();
  await page.getByTitle('Rate 3').locator('path').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('#permKycType').getByText('Aadhaar').click();
  await page.locator('#permAdd1Focus').getByRole('textbox').click();
  await page.locator('#permAdd1Focus').getByRole('textbox').fill('Test address 124 Main road');
  await page.getByLabel('', { exact: true }).first().click();
  await page.getByRole('searchbox').fill('maha');
  await page.getByRole('option', { name: 'Maharashtra' }).click();
  await page.getByRole('textbox', { name: '-- SELECT --' }).click();
  await page.getByRole('option', { name: 'Akola' }).click();
  await page.getByRole('textbox', { name: '-- SELECT --' }).click();
  await page.getByRole('option', { name: 'Akot' }).click();
  await page.getByRole('textbox', { name: '-- SELECT --' }).click();
  await page.getByRole('option', { name: 'Aurangabad Pr Akot' }).click();
  await page.locator('#perm_pincode').nth(1).click();
  await page.locator('#perm_pincode').nth(1).fill('400000');
  await page.locator('#copyAddress').check();
  await page.getByRole('button', { name: 'Save' }).click();
  await page.getByRole('button', { name: 'Generate Lead Score' }).click();
  await page.getByRole('button', { name: 'Close', exact: true }).click();
});